### ISSUE TITLE
Using redirect_to with markdown collections

### ISSUE THREAD

**Issue by zeke** [jekyll/jekyll-redirect-from#103]
:wave:

The Electron website has a build script that imports markdown files from the [electron/electron repo](https://github.com/electron/electron/tree/master/docs) and stores them in a `_docs` directory as a [collection](https://jekyllrb.com/docs/collections/).

We want to retire a bunch of URLs for older versions of the documentation, and redirect them to the latest. Here's a truncated example of the frontmatter in `_docs/api/dialog.md`:

```yml
---
version: v0.37.5
category: API
title: Dialog
redirect-from:
    - /docs/v0.37.3/api/dialog/
    - /docs/v0.37.4/api/dialog/
    - /docs/v0.37.5/api/dialog/
    - /docs/latest/api/dialog/
---
```

These redirects are not working. I tried simpler alternatives like `/test`, tried using fully-qualified URLs, tried setting `redirect-from` to a single string instead of an array of redirect strings, but no dice. Then I noticed this in the README:

> Note: if using `redirect_to` with collections, your collection's extension must end in `.html` in order for redirect_to to properly process.

My question: Is there a way to give a file a `.html` extension and still have Jekyll parse it as a markdown file? If not, would it be hard to add support for redirects to markdown files in collections?

cc @parkr @benbalter @gjtorikian who have been gracious with me so far in Slack, and [seem to have prior experience](https://github.com/jekyll/jekyll-redirect-from/pull/46) with this issue.
