### ISSUE TITLE
Support defining redirects in central _config.yml

### ISSUE THREAD

**Issue by danfowler** [jekyll/jekyll-redirect-from#118]
I currently have a GitHub Pages repo (https://github.com/frictionlessdata/specs) that has been updated drastically to redirect certain paths to another GitHub pages site entirely.  This requires the old paths to remain on the site with lots of `redirect_to`s to their new URLs.  It would be nice to define these redirects centrally in, say, the `_config.yml` file so that the repository is less cluttered.  Is this possible?

I imagine it would look something like this:

``` yaml
redirects:
  - from: /tabular-diff-format/
    to: http://specs.okfnlabs.org/tabular-diff-format/
  - from: /sleep/
    to: http://specs.okfnlabs.org/sleep/
```
