### ISSUE TITLE
Possible to add redirects using defaults in _config.yml?

### ISSUE THREAD

**Issue by retorquere** [jekyll/jekyll-redirect-from#176]
I'm trying to add redirects from my `_config.yml`, as my markdown pages are currently yaml-free (using `jekyll-default-layout`, `jekyll-titles-from-headings` and `jekyll-optional-front-matter`) like so:

```
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

repository: retorquere/zotero-better-bibtex

permalink: pretty

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

defaults:
  -
    scope:
      path: all-them-braces
    values:
      redirect_from:
        - /Unnecessarily-complicated-BibTeX-output/
        - /braces/
```

but I don't know if this can be made to work at all, and what I'd need to use for `path` here. Tips?
