### ISSUE TITLE
How to disable redirects.json?

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll-redirect-from#189]
Re #147 
I updated from an older Jekyll version and now my site has an extra `redirects.json` file. That lurks into sitemap and rss feed.

Question is simple how can I disable generating that file?

I tried this without luck:
```yaml
exclude:
  - redirects.json
```

**Comment by TWiStErRob** [comment]
also tried (with and without slash)
```yaml
defaults:
  -
    scope:
      path: '/redirects.json'
    values:
      sitemap: false
```
