### ISSUE TITLE
Redirect wildcard

### ISSUE THREAD

**Issue by zwhitchcox** [jekyll/jekyll-redirect-from#71]
This is my code from _config.yml

```yml
gems:
  - jekyll-redirect-from
redirect_from:
  - /*
  - /
```

with the intention of redirecting all requests to the index page. However, this is not working. Can someone please tell me the fix for this?
